package net.sahv.test01.mapper;

import java.util.List;
import net.sahv.blzy.model.Salary;

public interface SalaryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table salary
	 * @mbggenerated  Wed Jan 20 00:11:11 GMT+08:00 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table salary
	 * @mbggenerated  Wed Jan 20 00:11:11 GMT+08:00 2016
	 */
	int insert(Salary record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table salary
	 * @mbggenerated  Wed Jan 20 00:11:11 GMT+08:00 2016
	 */
	Salary selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table salary
	 * @mbggenerated  Wed Jan 20 00:11:11 GMT+08:00 2016
	 */
	List<Salary> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table salary
	 * @mbggenerated  Wed Jan 20 00:11:11 GMT+08:00 2016
	 */
	int updateByPrimaryKey(Salary record);
}