package net.sahv.blzy.model;

public class Salary {
    /**
     * ±àºÅ
     */
    private Integer id;

    /**
     * ÓÃ»§id
     */
    private Integer userId;

    /**
     * Ð½Ë®
     */
    private Long salary;

    private String name;

    private Long monthSale;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.id
     *
     * @return the value of salary.id
     *
     * @mbggenerated Wed Jan 20 00:11:11 GMT+08:00 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.id
     *
     * @param id the value for salary.id
     *
     * @mbggenerated Wed Jan 20 00:11:11 GMT+08:00 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.user_id
     *
     * @return the value of salary.user_id
     *
     * @mbggenerated Wed Jan 20 00:11:11 GMT+08:00 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.user_id
     *
     * @param userId the value for salary.user_id
     *
     * @mbggenerated Wed Jan 20 00:11:11 GMT+08:00 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.salary
     *
     * @return the value of salary.salary
     *
     * @mbggenerated Wed Jan 20 00:11:11 GMT+08:00 2016
     */
    public Long getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.salary
     *
     * @param salary the value for salary.salary
     *
     * @mbggenerated Wed Jan 20 00:11:11 GMT+08:00 2016
     */
    public void setSalary(Long salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.name
     *
     * @return the value of salary.name
     *
     * @mbggenerated Wed Jan 20 00:11:11 GMT+08:00 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.name
     *
     * @param name the value for salary.name
     *
     * @mbggenerated Wed Jan 20 00:11:11 GMT+08:00 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.month_sale
     *
     * @return the value of salary.month_sale
     *
     * @mbggenerated Wed Jan 20 00:11:11 GMT+08:00 2016
     */
    public Long getMonthSale() {
        return monthSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.month_sale
     *
     * @param monthSale the value for salary.month_sale
     *
     * @mbggenerated Wed Jan 20 00:11:11 GMT+08:00 2016
     */
    public void setMonthSale(Long monthSale) {
        this.monthSale = monthSale;
    }
}